"""Compact known-solution data for structured SILVA equilibrium families."""

from __future__ import annotations

from dataclasses import dataclass

import torch

Tensor = torch.Tensor


def _positive_integer(value: int, name: str) -> None:
    if value < 1:
        raise ValueError(f"{name} must be positive")


def _generator(seed: int) -> torch.Generator:
    return torch.Generator().manual_seed(seed)


def silva_chain_graph_operator(nodes: int, *, self_loops: bool = True) -> Tensor:
    """Return a symmetric normalized chain propagation matrix."""

    _positive_integer(nodes, "nodes")
    adjacency = torch.zeros(nodes, nodes)
    if nodes > 1:
        index = torch.arange(nodes - 1)
        adjacency[index, index + 1] = 1.0
        adjacency[index + 1, index] = 1.0
    if self_loops:
        adjacency.fill_diagonal_(1.0)
    degree = adjacency.sum(dim=1)
    inverse_sqrt = degree.clamp_min(1.0).rsqrt()
    return inverse_sqrt[:, None] * adjacency * inverse_sqrt[None, :]


def _fixed_point(
    transition,
    initial: Tensor,
    *,
    steps: int = 500,
    tol: float = 1e-10,
) -> Tensor:
    state = initial
    for _ in range(steps):
        updated = transition(state)
        if torch.linalg.vector_norm(updated - state) < tol:
            state = updated
            break
        state = updated
    return state


@dataclass
class SILVAMonotoneOperatorBatch:
    """Affine source and known monotone-ReLU equilibrium regression task."""

    inputs: Tensor
    target: Tensor
    equilibrium: Tensor
    recurrent: Tensor
    source: Tensor
    bias: Tensor
    readout: Tensor


def make_monotone_operator_dataset(
    *,
    samples: int = 48,
    in_dim: int = 4,
    state_dim: int = 6,
    out_dim: int = 2,
    seed: int = 81,
) -> SILVAMonotoneOperatorBatch:
    """Build a dense known-solution task satisfying a monotonicity margin."""

    for value, name in (
        (samples, "samples"),
        (in_dim, "in_dim"),
        (state_dim, "state_dim"),
        (out_dim, "out_dim"),
    ):
        _positive_integer(value, name)
    generator = _generator(seed)
    inputs = torch.randn(samples, in_dim, generator=generator)
    recurrent = 0.25 * torch.eye(state_dim)
    skew = 0.02 * torch.randn(state_dim, state_dim, generator=generator)
    recurrent = recurrent + skew - skew.transpose(0, 1)
    source = 0.35 * torch.randn(state_dim, in_dim, generator=generator)
    bias = 0.15 + 0.05 * torch.randn(state_dim, generator=generator)
    injection = inputs @ source.transpose(0, 1) + bias
    equilibrium = _fixed_point(
        lambda state: torch.relu(state @ recurrent.transpose(0, 1) + injection),
        torch.zeros_like(injection),
    )
    readout = 0.4 * torch.randn(out_dim, state_dim, generator=generator)
    target = equilibrium @ readout.transpose(0, 1)
    return SILVAMonotoneOperatorBatch(
        inputs,
        target,
        equilibrium,
        recurrent,
        source,
        bias,
        readout,
    )


@dataclass
class SILVAPositiveConcaveBatch:
    """Positive source, equilibrium, and output generated by a PC map."""

    inputs: Tensor
    target: Tensor
    equilibrium: Tensor
    positive_weight: Tensor
    source: Tensor
    bias: Tensor


def make_positive_concave_dataset(
    *,
    samples: int = 48,
    in_dim: int = 3,
    state_dim: int = 5,
    seed: int = 82,
) -> SILVAPositiveConcaveBatch:
    """Generate a bounded positive-concave tanh equilibrium."""

    for value, name in (
        (samples, "samples"),
        (in_dim, "in_dim"),
        (state_dim, "state_dim"),
    ):
        _positive_integer(value, name)
    generator = _generator(seed)
    inputs = torch.rand(samples, in_dim, generator=generator)
    positive_weight = 0.08 * torch.rand(
        state_dim, state_dim, generator=generator
    )
    source = 0.5 * torch.rand(state_dim, in_dim, generator=generator)
    bias = 0.1 + 0.05 * torch.rand(state_dim, generator=generator)
    injection = inputs @ source.transpose(0, 1) + bias
    equilibrium = _fixed_point(
        lambda state: torch.tanh(
            state @ positive_weight.transpose(0, 1) + injection
        ),
        torch.zeros_like(injection),
    )
    target = equilibrium.sum(dim=1, keepdim=True) / state_dim
    return SILVAPositiveConcaveBatch(
        inputs,
        target,
        equilibrium,
        positive_weight,
        source,
        bias,
    )


@dataclass
class SILVANonEuclideanBatch:
    """Nominal and perturbed inputs with exact weighted-infinity equilibria."""

    inputs: Tensor
    perturbed_inputs: Tensor
    equilibrium: Tensor
    perturbed_equilibrium: Tensor
    free_weight: Tensor
    metric: Tensor
    source: Tensor
    bias: Tensor
    perturbation_radius: float


def make_non_euclidean_robustness_dataset(
    *,
    samples: int = 40,
    in_dim: int = 4,
    state_dim: int = 6,
    perturbation_radius: float = 0.025,
    one_sided_bound: float = 0.05,
    seed: int = 83,
) -> SILVANonEuclideanBatch:
    """Generate a NEMON map and a bounded entrywise input perturbation."""

    for value, name in (
        (samples, "samples"),
        (in_dim, "in_dim"),
        (state_dim, "state_dim"),
    ):
        _positive_integer(value, name)
    if perturbation_radius <= 0.0:
        raise ValueError("perturbation_radius must be positive")
    if one_sided_bound >= 1.0:
        raise ValueError("one_sided_bound must be less than one")
    generator = _generator(seed)
    inputs = torch.randn(samples, in_dim, generator=generator)
    perturbation = perturbation_radius * torch.sign(
        torch.randn(samples, in_dim, generator=generator)
    )
    perturbed = inputs + perturbation
    free_weight = 0.04 * torch.randn(
        state_dim, state_dim, generator=generator
    )
    metric = torch.exp(0.15 * torch.randn(state_dim, generator=generator))
    transformed = free_weight * metric.unsqueeze(0) / metric.unsqueeze(1)
    recurrent = (
        transformed
        - torch.diag(free_weight.abs().sum(dim=1))
        + one_sided_bound * torch.eye(state_dim)
    )
    source = 0.2 * torch.randn(state_dim, in_dim, generator=generator)
    bias = 0.25 * torch.ones(state_dim)

    def solve(values: Tensor) -> Tensor:
        injection = values @ source.transpose(0, 1) + bias
        alpha = 0.5
        return _fixed_point(
            lambda state: (1.0 - alpha) * state
            + alpha
            * torch.relu(state @ recurrent.transpose(0, 1) + injection),
            torch.zeros(values.shape[0], state_dim),
        )

    equilibrium = solve(inputs)
    perturbed_equilibrium = solve(perturbed)
    return SILVANonEuclideanBatch(
        inputs,
        perturbed,
        equilibrium,
        perturbed_equilibrium,
        free_weight,
        metric,
        source,
        bias,
        perturbation_radius,
    )


@dataclass
class SILVAEfficientGraphBatch:
    """Chain graph, injected node features, and exact EIGNN equilibrium."""

    inputs: Tensor
    graph_operator: Tensor
    target: Tensor
    equilibrium: Tensor
    factor: Tensor
    gamma: float


def make_eignn_chain_dataset(
    *,
    nodes: int = 21,
    in_dim: int = 3,
    state_dim: int = 4,
    gamma: float = 0.8,
    seed: int = 84,
) -> SILVAEfficientGraphBatch:
    """Create a long-range chain regression target from the EIGNN equation."""

    for value, name in ((nodes, "nodes"), (in_dim, "in_dim"), (state_dim, "state_dim")):
        _positive_integer(value, name)
    if not 0.0 <= gamma < 1.0:
        raise ValueError("gamma must satisfy 0 <= gamma < 1")
    generator = _generator(seed)
    graph = silva_chain_graph_operator(nodes)
    inputs = 0.1 * torch.randn(nodes, in_dim, generator=generator)
    inputs[0, 0] = 1.0
    inputs[-1, min(1, in_dim - 1)] = -0.75
    source = torch.zeros(in_dim, state_dim)
    diagonal = min(in_dim, state_dim)
    source[:diagonal, :diagonal] = torch.eye(diagonal)
    injection = inputs @ source
    factor = torch.eye(state_dim)
    gram = factor.transpose(0, 1) @ factor
    gram = gram / torch.linalg.matrix_norm(gram, ord="fro")
    equilibrium = _fixed_point(
        lambda state: gamma * (graph.transpose(0, 1) @ state @ gram) + injection,
        torch.zeros(nodes, state_dim),
    )
    target = equilibrium[:, :1]
    return SILVAEfficientGraphBatch(
        inputs,
        graph,
        target,
        equilibrium,
        factor,
        gamma,
    )


@dataclass
class SILVAMultiscaleGraphBatch:
    """Graph signals and a target combining one-hop and multi-hop equilibria."""

    inputs: Tensor
    graph_operator: Tensor
    target: Tensor
    scale_states: tuple[Tensor, ...]
    target_weights: Tensor
    scales: tuple[int, ...]
    gamma: float


def make_mgnni_multiscale_dataset(
    *,
    nodes: int = 24,
    in_dim: int = 3,
    state_dim: int = 4,
    scales: tuple[int, ...] = (1, 2, 3),
    gamma: float = 0.75,
    seed: int = 85,
) -> SILVAMultiscaleGraphBatch:
    """Create a chain target with node-dependent preferences over graph scales."""

    for value, name in ((nodes, "nodes"), (in_dim, "in_dim"), (state_dim, "state_dim")):
        _positive_integer(value, name)
    if not scales or any(scale < 1 for scale in scales):
        raise ValueError("scales must contain positive integers")
    if not 0.0 <= gamma < 1.0:
        raise ValueError("gamma must satisfy 0 <= gamma < 1")
    generator = _generator(seed)
    graph = silva_chain_graph_operator(nodes)
    inputs = 0.05 * torch.randn(nodes, in_dim, generator=generator)
    inputs[0, 0] = 1.0
    inputs[nodes // 2, min(1, in_dim - 1)] = 1.0
    source = torch.zeros(in_dim, state_dim)
    diagonal = min(in_dim, state_dim)
    source[:diagonal, :diagonal] = torch.eye(diagonal)
    injection = inputs @ source
    gram = torch.eye(state_dim) / state_dim**0.5
    scale_states: list[Tensor] = []
    for scale in scales:
        graph_power = torch.linalg.matrix_power(graph, scale)
        state = _fixed_point(
            lambda value, graph_power=graph_power: gamma
            * (graph_power.transpose(0, 1) @ value @ gram)
            + injection,
            torch.zeros(nodes, state_dim),
        )
        scale_states.append(state)
    positions = torch.linspace(-1.0, 1.0, nodes)
    logits = torch.stack(
        [-(positions - center).square() for center in torch.linspace(-0.8, 0.8, len(scales))],
        dim=1,
    )
    target_weights = torch.softmax(3.0 * logits, dim=1)
    stacked = torch.stack(scale_states, dim=1)
    fused = (target_weights.unsqueeze(-1) * stacked).sum(dim=1)
    target = fused[:, :1]
    return SILVAMultiscaleGraphBatch(
        inputs,
        graph,
        target,
        tuple(scale_states),
        target_weights,
        tuple(scales),
        gamma,
    )


@dataclass
class SILVADeltaConvergenceBatch:
    """Affine equilibrium with coordinates converging at different rates."""

    inputs: Tensor
    target: Tensor
    equilibrium: Tensor
    rates: Tensor
    source: Tensor
    bias: Tensor


def make_delta_heterogeneous_dataset(
    *,
    samples: int = 32,
    in_dim: int = 3,
    state_dim: int = 6,
    seed: int = 86,
) -> SILVADeltaConvergenceBatch:
    """Generate a linear fixed point with slow and fast latent coordinates."""

    for value, name in (
        (samples, "samples"),
        (in_dim, "in_dim"),
        (state_dim, "state_dim"),
    ):
        _positive_integer(value, name)
    generator = _generator(seed)
    inputs = torch.randn(samples, in_dim, generator=generator)
    rates = torch.linspace(0.1, 0.92, state_dim)
    source = 0.15 * torch.randn(state_dim, in_dim, generator=generator)
    bias = 0.05 * torch.randn(state_dim, generator=generator)
    injection = inputs @ source.transpose(0, 1) + bias
    equilibrium = injection / (1.0 - rates)
    target = equilibrium.mean(dim=1, keepdim=True)
    return SILVADeltaConvergenceBatch(
        inputs,
        target,
        equilibrium,
        rates,
        source,
        bias,
    )


__all__ = [
    "SILVADeltaConvergenceBatch",
    "SILVAEfficientGraphBatch",
    "SILVAMonotoneOperatorBatch",
    "SILVAMultiscaleGraphBatch",
    "SILVANonEuclideanBatch",
    "SILVAPositiveConcaveBatch",
    "make_delta_heterogeneous_dataset",
    "make_eignn_chain_dataset",
    "make_mgnni_multiscale_dataset",
    "make_monotone_operator_dataset",
    "make_non_euclidean_robustness_dataset",
    "make_positive_concave_dataset",
    "silva_chain_graph_operator",
]
